[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
governance = "AGP7BofJoJco4wTR6jaM1mf28z2UuV6Xj9aN4RBY9gnK"
otc_market = "6FM7VKFLyzxubAhCY58rR1R42tuuVNY7QdAtNTq65EjN"
project_escrow = "bJch5cLcCHTypbXrvRMr9MxU5HmN2LBRwF8wR4dXpym"
revenue_distribution = "C7qE7zNk7YA9rLhqRejFpMPH9y2Ds8rYZs2WEyhxUUWK"
rwa_token = "GqSR1FPPjaTH4hzjm5kpejh3dUdTQtdufaz1scU5ZkvE"
rwa_transfer_hook = "HAC2Q2ecWgDXHt34bs1afuGqUsKfxycqd2MXuWHkRgRj"
taste_token = "2c6qsaK5o1mjUxSvJmfCDzfCcaim8c9hEmNZrBbc4Bxo"

[programs.localnet]
governance = "AWYFhCcwsnMAsBRBRcTyFYHJBPmUJwfx2WxKGDgLap79"
otc_market = "Gm3e8Ky9mLBe2bjNbMh3qA3oVvaRca4p9BKKv3dLY7dD"
project_escrow = "EumKWobeYfq9Lx9zwVjfJvaghYC321cxENEcasKfuRrK"
revenue_distribution = "dWGsAdXVDbU7oEoZPKu5rbCBDnSLvaoCjLAXBVr7i7Q"
rwa_token = "8PTbAHnemqCN8gnvMqkUfa3SUkHAR7zFcLQsxryq7BoS"
rwa_transfer_hook = "56LtERCqfVTv84E2AtL3jrKBdFXD8QxQN74NmoyJjBPn"
taste_token = "6cK45rigmh2Yj4aTGhmCmoxc85KFUepQfXjxehWCEAQM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/governance", "programs/otc_market", "programs/project_escrow", "programs/revenue_distribution", "programs/rwa_token", "programs/taste_token"]

[scripts]
test = "bash scripts/run-mocha.sh"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "test-programs/metadata.so"
