[toolchain]
anchor_version = "0.32.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
governance = "AGP7BofJoJco4wTR6jaM1mf28z2UuV6Xj9aN4RBY9gnK"
otc_market = "6FM7VKFLyzxubAhCY58rR1R42tuuVNY7QdAtNTq65EjN"
project_escrow = "bJch5cLcCHTypbXrvRMr9MxU5HmN2LBRwF8wR4dXpym"
revenue_distribution = "6bckDfoEDZWgZXU66fL2Sq6pjFmqxk3JVZEs2YVYMLc3"
rwa_token = "GqSR1FPPjaTH4hzjm5kpejh3dUdTQtdufaz1scU5ZkvE"
rwa_transfer_hook = "56LtERCqfVTv84E2AtL3jrKBdFXD8QxQN74NmoyJjBPn"
taste_token = "2c6qsaK5o1mjUxSvJmfCDzfCcaim8c9hEmNZrBbc4Bxo"

[programs.localnet]
governance = "2hfuv5tWYuAfMxgKDAcUMU7tEQdFhWALRqakB8BagHev"
otc_market = "5urCev8TEJBZ4gk4RNH2G5eH9tQ8h5yFc2jg8hGnZF4Q"
project_escrow = "A84LLpCwTZ98h1nJxbzoXvb4UhbWCeSmJwnkCXY7JFnK"
revenue_distribution = "4RXKpphnRMC4yTpkjVLKQqMgFdHere6kC3BjZssPQmfR"
rwa_token = "2qqPrgzUBfG1s1gCQtNtp3ZhMDqJNhmQ6J9uo4Mbuq9h"
rwa_transfer_hook = "56LtERCqfVTv84E2AtL3jrKBdFXD8QxQN74NmoyJjBPn"
taste_token = "ABWg7aLc5s9rin32nFVudwwJB77DDdSMPq9Ta5LkezWT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/governance", "programs/otc_market", "programs/project_escrow", "programs/revenue_distribution", "programs/rwa_token", "programs/taste_token"]

[scripts]
test = "bash scripts/run-mocha.sh"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "test-programs/metadata.so"
